
SELECT 
 'BASE DE DATOS 2' MATERIA
,'OSCAR ENCARNACION' PROFESOR
,'DDL1' TAREA
,'PABLO OTTONIEL PEREZ SANCHEZ' ESTUDIANTE
,'100201585' NIP
,'201901' SEMESTRE
,'UASD' UNIVERSIDAD

GO 
DROP TABLE ESCUELA
GO
CREATE TABLE ESCUELA(
	ESCUELA_IDENTI INT NOT NULL IDENTITY,
	ESCUELA_NOMBRE NVARCHAR(100) NOT NULL,
	ESCUELA_TELEFO NVARCHAR(15) NOT NULL,
	 
	CONSTRAINT [PK_ESCUELA] PRIMARY KEY CLUSTERED (
		ESCUELA_IDENTI DESC
	)
)
SET Identity_Insert ESCUELA ON
---------------------------------------
 
GO 
DROP TABLE GUIA
GO
CREATE TABLE GUIA(
	GUIA_IDENTI INT NOT NULL IDENTITY,
	GUIA_NOMBRE NVARCHAR(100) NOT NULL, 
	 
	CONSTRAINT [PK_GUIA] PRIMARY KEY CLUSTERED (
		GUIA_IDENTI DESC
	)
)
SET Identity_Insert GUIA ON
---------------------------------------
 
GO 
DROP TABLE RESERVA
GO
CREATE TABLE RESERVA(
	RESERVA_IDENTI INT NOT NULL IDENTITY,
	RESERVA_FECHA DATETIME2(7) NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	 
	CONSTRAINT [PK_RESERVA] PRIMARY KEY CLUSTERED (
		RESERVA_IDENTI DESC
	)
)
SET Identity_Insert RESERVA ON
---------------------------------------
 
GO 
DROP TABLE RESERVA
GO
CREATE TABLE RESERVA(
	RESERVA_IDENTI INT NOT NULL IDENTITY,
	ESCUELA_IDENTI INT NOT NULL ,
	RESERVA_FECHA DATETIME2(7) NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	 
	CONSTRAINT [PK_RESERVA] PRIMARY KEY CLUSTERED (
		RESERVA_IDENTI DESC
	)
)
SET Identity_Insert RESERVA ON
---------------------------------------
 
GO 
DROP TABLE RESERVA_TIPO_VISITA
GO
CREATE TABLE RESERVA_TIPO_VISITA(
	RETIPVI_IDENTI INT NOT NULL IDENTITY,
	RESERVA_IDENTI INT NOT NULL ,
	TIPVISI_IDENTI INT NOT NULL , 
	 
	CONSTRAINT [PK_RETIPVI] PRIMARY KEY CLUSTERED (
		RETIPVI_IDENTI DESC
	)
)
SET Identity_Insert RETIPVI ON
 
--------------------------------------------
GO
DROP TABLE TELEFONO_ESCUELA
GO
CREATE TABLE TELEFONO_ESCUELA(
	TELEESC_IDENTI	INT NOT NULL IDENTITY,
	TELEESC_AREA	NVARCHAR(100) NOT NULL,
	TELEESC_NUMERO	NVARCHAR(15) NOT NULL,
	 
	CONSTRAINT [PK_TELEESC] PRIMARY KEY CLUSTERED (
		TELEESC_IDENTI DESC,
		TELEESC_AREA,
		TELEESC_NUMERO
	)
)
SET Identity_Insert TELEFONO_ESCUELA ON

GO

INSERT INTO TELEFONO_ESCUELA (TELEESC_IDENTI,TELEESC_AREA,TELEESC_NUMERO)
VALUES(1, 243,2)
--SELECT * FROM TELEFONO_ESCUELA 




